// Auto-generated by: bun run gen:types
// DO NOT EDIT MANUALLY

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          plan: 'free' | 'pro' | 'enterprise'
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['profiles']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['profiles']['Insert']>
      }
      generated_emails: {
        Row: {
          id: string
          user_id: string
          subject: string
          tone: 'professional' | 'casual' | 'formal' | 'friendly' | 'persuasive'
          length: 'short' | 'medium' | 'long'
          content: string
          model_used: string
          tokens_used: number | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['generated_emails']['Row'], 'id' | 'created_at'>
        Update: Partial<Database['public']['Tables']['generated_emails']['Insert']>
      }
    }
  }
}
