// Auto-generated by: bun run gen:types
// DO NOT EDIT MANUALLY

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          plan: 'free' | 'pro' | 'enterprise'
          created_at: string
          updated_at: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          stripe_price_id: string | null
          stripe_current_period_end: string | null
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          plan?: 'free' | 'pro' | 'enterprise'
          created_at?: string
          updated_at?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          stripe_price_id?: string | null
          stripe_current_period_end?: string | null
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          plan?: 'free' | 'pro' | 'enterprise'
          created_at?: string
          updated_at?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          stripe_price_id?: string | null
          stripe_current_period_end?: string | null
        }
        Relationships: []
      }
      generated_emails: {
        Row: {
          id: string
          user_id: string
          subject: string
          tone: 'professional' | 'casual' | 'formal' | 'friendly' | 'persuasive'
          length: 'short' | 'medium' | 'long'
          content: string
          model_used: string
          tokens_used: number | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          subject: string
          tone: 'professional' | 'casual' | 'formal' | 'friendly' | 'persuasive'
          length: 'short' | 'medium' | 'long'
          content: string
          model_used?: string
          tokens_used?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          subject?: string
          tone?: 'professional' | 'casual' | 'formal' | 'friendly' | 'persuasive'
          length?: 'short' | 'medium' | 'long'
          content?: string
          model_used?: string
          tokens_used?: number | null
          created_at?: string
        }
        Relationships: []
      }
    }
    Views: Record<never, never>
    Functions: Record<never, never>
    Enums: Record<never, never>
    CompositeTypes: Record<never, never>
  }
}
